name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webdav:alpine .
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/webdav:alpine

